### ISSUE TITLE
Possible passport-twitter issue

### ISSUE THREAD

**Issue by pentachen** [slkaczma/iot-foosball#2]
I ran into an issue where my Twitter sessions would not be destroyed/my Twitter users would not be logged out after signing in to play.  This could have been due to res.redirect('/'); firing before req.logout(); finishes in **server.js**.

My workaround was to either replace
`app.get('/login/twitter',passport.authenticate('twitter'));`
with 
`app.get('/login/twitter',passport.authenticate('twitter', { forceLogin: true }));`

or replace
`app.get('/login/twitter/return',`
`passport.authenticate('twitter', { failureRedirect: '/' }),`
`function(req, res) {`
`req.logout();`
`res.redirect('/');`
`});`
with
`app.get('/login/twitter/return',`
`passport.authenticate('twitter', { failureRedirect: '/' }),`
`function(req, res) {`
`req.session.destroy(); //is this bad practice?`
`res.redirect('/');`
`});`

**Comment by sharpstef** [comment]
We typically do browsers in incognito mode for this, but adding in your forceLogin fix! Thanks!
